import { BookingRequest, Guest, Property, Review, SiteSettings } from '../../types';

export const AVAILABLE_AMENITIES = [
  'High-Speed Fiber Wi-Fi',
  'Dedicated Workspace',
  'Heated Swimming Pool',
  'Free Secure Parking',
  'Fully Equipped Kitchen',
  'Smart 4K TV',
  'Air Conditioning',
  'Washing Machine & Dryer',
  '24/7 Manned Security & CCTV',
  'Full Backup Power Generator',
  'Private Balcony / Veranda',
  'Kenyan AA Coffee & Tea Bar',
];

export const INITIAL_SETTINGS: SiteSettings = {
  whatsapp_number: (import.meta as unknown as { env: Record<string, string> }).env?.VITE_RAFIKI_WHATSAPP || '254712345678',
  phone_number: (import.meta as unknown as { env: Record<string, string> }).env?.VITE_RAFIKI_PHONE || '+254 712 345 678',
  support_email: 'karibu@rafikiliving.com',
  office_address: 'Argwings Kodhek Road, Kilimani, Nairobi, Kenya',
  company_tagline: 'Where Every Stay Feels Like Home.',
};

// Curated SVG / High-resolution architectural visuals for each property
export const PROPERTY_VISUAL_STYLES: Record<string, { bg: string; accent: string; label: string }> = {
  'prop-rafiki-heights': {
    bg: 'from-[#2C4C3E] via-[#375A4B] to-[#1E372C]',
    accent: '#B89758',
    label: 'Kilimani Jacaranda Skyline Suite',
  },
  'prop-rafiki-haven': {
    bg: 'from-[#4A3B32] via-[#5C4B40] to-[#362A23]',
    accent: '#D4AF37',
    label: 'Kileleshwa Garden Residence',
  },
  'prop-rafiki-urban': {
    bg: 'from-[#1E293B] via-[#334155] to-[#0F172A]',
    accent: '#38BDF8',
    label: 'Westlands Executive Loft',
  },
};

export const INITIAL_PROPERTIES: Property[] = [
  {
    id: 'prop-rafiki-heights',
    name: 'Rafiki Heights',
    slug: 'rafiki-heights',
    description:
      'Perched on a quiet leafy rise in Kilimani, Rafiki Heights is a sun-drenched two-bedroom residence crafted for discerning travelers, diplomats, and remote executives. Floor-to-ceiling windows frame Nairobi’s jacaranda canopy while handcrafted East African teak furnishings, woven sisal textures, and a chef-ready kitchen create a calm, restorative sanctuary after a day in the city.',
    neighborhood_overview:
      'Located in central Kilimani within a 6-minute walk of Yaya Centre, artisanal cafés, and organic grocers. 15 minutes to Nairobi National Park and 25 minutes to Jomo Kenyatta International Airport via the Nairobi Expressway.',
    location: 'Kilimani',
    city: 'Nairobi',
    country: 'Kenya',
    price_per_night: 8500,
    max_guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    property_type: 'Boutique Apartment',
    amenities: [
      'High-Speed Fiber Wi-Fi',
      'Dedicated Workspace',
      'Heated Swimming Pool',
      'Free Secure Parking',
      'Fully Equipped Kitchen',
      'Smart 4K TV',
      'Washing Machine & Dryer',
      '24/7 Manned Security & CCTV',
      'Full Backup Power Generator',
      'Private Balcony / Veranda',
      'Kenyan AA Coffee & Tea Bar',
    ],
    house_rules: {
      smoking: 'No smoking inside the apartment or on the balcony',
      pets: 'Pets are not permitted',
      parties: 'No parties, events, or unregistered overnight guests',
      quiet_hours: 'Quiet hours observed between 10:00 PM and 7:00 AM',
      other: 'Passport or national ID copy required prior to check-in for building security registration',
    },
    check_in_time: '2:00 PM',
    check_out_time: '11:00 AM',
    featured: true,
    published: true,
    is_demo: true,
    rating: 4.9,
    review_count: 2,
    images: [
      {
        id: 'img-heights-1',
        property_id: 'prop-rafiki-heights',
        url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1600&q=80',
        alt: 'Rafiki Heights sunlit living room overlooking Kilimani trees',
        is_cover: true,
        display_order: 0,
      },
      {
        id: 'img-heights-2',
        property_id: 'prop-rafiki-heights',
        url: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1200&q=80',
        alt: 'Rafiki Heights serene master bedroom with organic linen',
        is_cover: false,
        display_order: 1,
      },
      {
        id: 'img-heights-3',
        property_id: 'prop-rafiki-heights',
        url: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80',
        alt: 'Rafiki Heights sunset rooftop terrace and plunge pool',
        is_cover: false,
        display_order: 2,
      },
      {
        id: 'img-heights-4',
        property_id: 'prop-rafiki-heights',
        url: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80',
        alt: 'Rafiki Heights chef-ready modern kitchen and breakfast counter',
        is_cover: false,
        display_order: 3,
      },
    ],
    created_at: '2026-09-01T10:00:00Z',
    updated_at: '2026-10-01T10:00:00Z',
  },
  {
    id: 'prop-rafiki-haven',
    name: 'Rafiki Haven',
    slug: 'rafiki-haven',
    description:
      'Tucked inside a tranquil gated courtyard in Kileleshwa, Rafiki Haven offers the warmth of a private Kenyan garden home with three generous bedrooms, a wrap-around cedar veranda, and effortless indoor-outdoor living. Ideal for families, relocating expats, or small groups starting or concluding an East African safari.',
    neighborhood_overview:
      'Situated in leafy Kileleshwa near the Nairobi Arboretum walking trails. Peaceful residential ambiance with quick access to Lavington green spaces and Westlands dining.',
    location: 'Kileleshwa',
    city: 'Nairobi',
    country: 'Kenya',
    price_per_night: 13500,
    max_guests: 6,
    bedrooms: 3,
    beds: 4,
    bathrooms: 3,
    property_type: 'Garden Residence',
    amenities: [
      'High-Speed Fiber Wi-Fi',
      'Free Secure Parking',
      'Fully Equipped Kitchen',
      'Smart 4K TV',
      'Washing Machine & Dryer',
      '24/7 Manned Security & CCTV',
      'Full Backup Power Generator',
      'Private Balcony / Veranda',
      'Kenyan AA Coffee & Tea Bar',
      'Dedicated Workspace',
    ],
    house_rules: {
      smoking: 'Smoking permitted only in designated outdoor garden area',
      pets: 'Pets are not permitted',
      parties: 'No commercial photography or large gatherings without prior written approval',
      quiet_hours: 'Quiet hours observed between 10:00 PM and 7:00 AM',
      other: 'Registered guests only within the gated compound',
    },
    check_in_time: '2:00 PM',
    check_out_time: '11:00 AM',
    featured: true,
    published: true,
    is_demo: true,
    rating: 5.0,
    review_count: 2,
    images: [
      {
        id: 'img-haven-1',
        property_id: 'prop-rafiki-haven',
        url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80',
        alt: 'Rafiki Haven garden veranda with stone pillars and linen seating',
        is_cover: true,
        display_order: 0,
      },
      {
        id: 'img-haven-2',
        property_id: 'prop-rafiki-haven',
        url: 'https://images.unsplash.com/photo-1600565193348-f74bd3c7ccdf?auto=format&fit=crop&w=1200&q=80',
        alt: 'Rafiki Haven warm dining and living lounge',
        is_cover: false,
        display_order: 1,
      },
      {
        id: 'img-haven-3',
        property_id: 'prop-rafiki-haven',
        url: 'https://images.unsplash.com/photo-1617325247661-675ab4b64ae2?auto=format&fit=crop&w=1200&q=80',
        alt: 'Rafiki Haven master bedroom looking out to the garden',
        is_cover: false,
        display_order: 2,
      },
      {
        id: 'img-haven-4',
        property_id: 'prop-rafiki-haven',
        url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
        alt: 'Rafiki Haven tranquil private courtyard',
        is_cover: false,
        display_order: 3,
      },
    ],
    created_at: '2026-09-05T10:00:00Z',
    updated_at: '2026-10-02T10:00:00Z',
  },
  {
    id: 'prop-rafiki-urban',
    name: 'Rafiki Urban',
    slug: 'rafiki-urban',
    description:
      'Designed for international business travelers and couples visiting Nairobi, Rafiki Urban is an architectural one-bedroom suite in the heart of Westlands. Featuring a bespoke solid oak workstation, dual-ISP fiber internet, full generator backup, air conditioning, and access to a heated rooftop plunge pool.',
    neighborhood_overview:
      'Located in the diplomatic and culinary hub of Westlands, moments from UN Avenue links, Sarit Centre, and Nairobi’s premier restaurants, contemporary art galleries, and executive offices.',
    location: 'Westlands',
    city: 'Nairobi',
    country: 'Kenya',
    price_per_night: 7500,
    max_guests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1.5,
    property_type: 'Executive Suite',
    amenities: [
      'High-Speed Fiber Wi-Fi',
      'Dedicated Workspace',
      'Heated Swimming Pool',
      'Free Secure Parking',
      'Fully Equipped Kitchen',
      'Smart 4K TV',
      'Air Conditioning',
      'Washing Machine & Dryer',
      '24/7 Manned Security & CCTV',
      'Full Backup Power Generator',
      'Kenyan AA Coffee & Tea Bar',
    ],
    house_rules: {
      smoking: 'Strictly non-smoking residence',
      pets: 'Pets are not permitted',
      parties: 'No parties or events allowed',
      quiet_hours: 'Quiet hours observed between 10:00 PM and 7:00 AM',
      other: 'Express self check-in or personal concierge meet-and-greet available',
    },
    check_in_time: '2:00 PM',
    check_out_time: '11:00 AM',
    featured: true,
    published: true,
    is_demo: true,
    rating: 4.9,
    review_count: 1,
    images: [
      {
        id: 'img-urban-1',
        property_id: 'prop-rafiki-urban',
        url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1600&q=80',
        alt: 'Rafiki Urban executive workspace and dining suite in Westlands',
        is_cover: true,
        display_order: 0,
      },
      {
        id: 'img-urban-2',
        property_id: 'prop-rafiki-urban',
        url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80',
        alt: 'Rafiki Urban solid oak workspace and modern media lounge',
        is_cover: false,
        display_order: 1,
      },
      {
        id: 'img-urban-3',
        property_id: 'prop-rafiki-urban',
        url: 'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1200&q=80',
        alt: 'Rafiki Urban king bedroom with warm timber details',
        is_cover: false,
        display_order: 2,
      },
    ],
    created_at: '2026-09-10T10:00:00Z',
    updated_at: '2026-10-03T10:00:00Z',
  },
];

export const INITIAL_GUESTS: Guest[] = [
  {
    id: 'guest-1',
    full_name: 'John Smith',
    email: 'john.smith@example.co.uk',
    phone: '+44 7700 900412',
    created_at: '2026-10-06T14:20:00Z',
  },
  {
    id: 'guest-2',
    full_name: 'Clara Lindqvist',
    email: 'clara.lindqvist@nordicventures.se',
    phone: '+254 722 891 304',
    created_at: '2026-10-04T09:15:00Z',
  },
  {
    id: 'guest-3',
    full_name: 'Marcus Vance',
    email: 'mvance@globalhealth.org',
    phone: '+1 202 555 0184',
    created_at: '2026-10-07T18:40:00Z',
  },
];

export const INITIAL_BOOKINGS: BookingRequest[] = [
  {
    id: 'bk-2026-0012',
    reference_number: 'RFL-2026-0012',
    property_id: 'prop-rafiki-heights',
    property_name: 'Rafiki Heights',
    property_slug: 'rafiki-heights',
    property_location: 'Kilimani, Nairobi',
    guest_id: 'guest-1',
    guest_name: 'John Smith',
    guest_email: 'john.smith@example.co.uk',
    guest_phone: '447700900412',
    check_in: '2026-10-15',
    check_out: '2026-10-19',
    guests_count: 2,
    total_nights: 4,
    estimated_total: 34000,
    special_requests: 'Arriving on British Airways flight BA65 at 9:30 PM. Would appreciate airport transfer coordination if available.',
    status: 'pending',
    admin_notes: 'Demo booking request — awaiting WhatsApp confirmation with guest.',
    created_at: '2026-10-06T14:20:00Z',
    updated_at: '2026-10-06T14:20:00Z',
  },
  {
    id: 'bk-2026-0011',
    reference_number: 'RFL-2026-0011',
    property_id: 'prop-rafiki-haven',
    property_name: 'Rafiki Haven',
    property_slug: 'rafiki-haven',
    property_location: 'Kileleshwa, Nairobi',
    guest_id: 'guest-2',
    guest_name: 'Clara Lindqvist',
    guest_email: 'clara.lindqvist@nordicventures.se',
    guest_phone: '254722891304',
    check_in: '2026-10-22',
    check_out: '2026-10-27',
    guests_count: 4,
    total_nights: 5,
    estimated_total: 67500,
    special_requests: 'Traveling with two colleagues before heading to Maasai Mara. Early check-in around 12:30 PM if possible.',
    status: 'confirmed',
    admin_notes: 'Confirmed via WhatsApp. Deposit received via M-Pesa. Driver Benson assigned for JKIA pickup.',
    created_at: '2026-10-04T09:15:00Z',
    updated_at: '2026-10-05T11:00:00Z',
  },
  {
    id: 'bk-2026-0013',
    reference_number: 'RFL-2026-0013',
    property_id: 'prop-rafiki-urban',
    property_name: 'Rafiki Urban',
    property_slug: 'rafiki-urban',
    property_location: 'Westlands, Nairobi',
    guest_id: 'guest-3',
    guest_name: 'Marcus Vance',
    guest_email: 'mvance@globalhealth.org',
    guest_phone: '12025550184',
    check_in: '2026-11-02',
    check_out: '2026-11-07',
    guests_count: 1,
    total_nights: 5,
    estimated_total: 37500,
    special_requests: 'Attending UN Gigiri & Westlands regional conference. Need reliable fiber Wi-Fi for morning video calls.',
    status: 'contacted',
    admin_notes: 'Sent WhatsApp message with corporate invoice details.',
    created_at: '2026-10-07T18:40:00Z',
    updated_at: '2026-10-08T08:10:00Z',
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    property_id: 'prop-rafiki-heights',
    property_name: 'Rafiki Heights',
    guest_name: 'Elena Rostova',
    guest_origin: 'Zurich, Switzerland · 6-night stay',
    rating: 5,
    comment:
      'Rafiki Heights felt like a private sanctuary in Kilimani. Prior to our arrival, the team coordinated our airport pickup via WhatsApp and stocked the kitchen with fresh Kenyan AA coffee. The fiber internet never dropped once during our remote work week.',
    stay_date: 'September 2026',
    published: true,
    created_at: '2026-09-20T12:00:00Z',
  },
  {
    id: 'rev-2',
    property_id: 'prop-rafiki-heights',
    property_name: 'Rafiki Heights',
    guest_name: 'David & Sarah Miller',
    guest_origin: 'London, United Kingdom · 4-night stay',
    rating: 5,
    comment:
      'We stayed here before and after our Amboseli safari. Impeccably clean, warm lighting, genuinely comfortable beds, and 24-hour security that made us feel completely at ease in Nairobi.',
    stay_date: 'September 2026',
    published: true,
    created_at: '2026-09-28T15:30:00Z',
  },
  {
    id: 'rev-3',
    property_id: 'prop-rafiki-haven',
    property_name: 'Rafiki Haven',
    guest_name: 'Dr. Henrik Lindholm',
    guest_origin: 'Stockholm, Sweden · 10-night relocation stay',
    rating: 5,
    comment:
      'Moving our family to Nairobi for a diplomatic posting was stressful until we checked into Rafiki Haven. Having three proper bedrooms and a quiet garden veranda in Kileleshwa gave us a true home base.',
    stay_date: 'August 2026',
    published: true,
    created_at: '2026-08-29T10:00:00Z',
  },
  {
    id: 'rev-4',
    property_id: 'prop-rafiki-haven',
    property_name: 'Rafiki Haven',
    guest_name: 'Amara Okafor',
    guest_origin: 'Lagos & London · 5-night stay',
    rating: 5,
    comment:
      'Thoughtful hospitality from start to finish. Instead of an impersonal lockbox experience, Rafiki Airbnbs checked in on us via WhatsApp and arranged a late check-out before our evening flight.',
    stay_date: 'September 2026',
    published: true,
    created_at: '2026-09-14T16:45:00Z',
  },
  {
    id: 'rev-5',
    property_id: 'prop-rafiki-urban',
    property_name: 'Rafiki Urban',
    guest_name: 'Thomas Beaumont',
    guest_origin: 'Paris, France · 5-night business stay',
    rating: 5,
    comment:
      'Far superior to a standard business hotel in Westlands. The solid oak desk, backup generator, and quiet bedroom allowed me to work seamlessly, with Nairobi’s best restaurants five minutes away.',
    stay_date: 'September 2026',
    published: true,
    created_at: '2026-09-25T09:15:00Z',
  },
];

export const KENYA_DESTINATIONS_META: Record<
  string,
  { city: string; description: string; highlights: string[]; defaultImage: string }
> = {
  Kilimani: {
    city: 'Nairobi',
    description:
      'A leafy, cosmopolitan neighborhood blending quiet residential avenues with specialty coffee roasters, contemporary galleries, and effortless access to central Nairobi.',
    highlights: ['6 min to Yaya Centre', '15 min to Nairobi National Park', '25 min to JKIA via Expressway'],
    defaultImage: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80',
  },
  Kileleshwa: {
    city: 'Nairobi',
    description:
      'Known for its mature jacaranda trees, spacious garden compounds, and proximity to the Nairobi Arboretum walking trails—ideal for families and longer stays.',
    highlights: ['Adjacent to Nairobi Arboretum', 'Quiet gated avenues', '10 min to Westlands & Lavington'],
    defaultImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
  },
  Westlands: {
    city: 'Nairobi',
    description:
      'Nairobi’s vibrant diplomatic, culinary, and commercial district—offering walkable access to top dining, executive offices, and UN Gigiri links.',
    highlights: ['Premier dining & cafés', '12 min to UN Gigiri', 'Direct Expressway airport link'],
    defaultImage: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80',
  },
  Nairobi: {
    city: 'Nairobi',
    description:
      'East Africa’s dynamic capital and safari gateway, where modern architectural living meets lush urban forests and warm Kenyan hospitality.',
    highlights: ['Safari gateway capital', 'Year-round temperate climate', 'World-class dining & culture'],
    defaultImage: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=800&q=80',
  },
  Diani: {
    city: 'Diani',
    description:
      'Powdery white coral sands and warm Indian Ocean waters along Kenya’s south coast, framed by coastal forest.',
    highlights: ['Indian Ocean beachfront', 'Kite surfing & marine reserve', 'Ukunda airstrip access'],
    defaultImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
  },
  Mombasa: {
    city: 'Mombasa',
    description:
      'Historic Swahili coastal architecture, breezy oceanfront residences, and centuries of Indian Ocean trade culture.',
    highlights: ['Swahili coastal heritage', 'Nyali & English Point', 'SGR & Moi International Airport'],
    defaultImage: 'https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?auto=format&fit=crop&w=800&q=80',
  },
  Naivasha: {
    city: 'Naivasha',
    description:
      'Great Rift Valley lakefront sanctuaries surrounded by fever trees, wildlife conservancies, and geothermal spas.',
    highlights: ['90 min from Nairobi', 'Hell’s Gate & Crater Lake', 'Private golf & wildlife estates'],
    defaultImage: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80',
  },
  Nanyuki: {
    city: 'Nanyuki',
    description:
      'High-altitude foothills of Mount Kenya offering crisp equatorial air and direct access to Ol Pejeta and Lewa conservancies.',
    highlights: ['Views of Mount Kenya', 'Ol Pejeta Conservancy access', 'Nanyuki airstrip links'],
    defaultImage: 'https://images.unsplash.com/photo-1489392191049-fc10c97e64b6?auto=format&fit=crop&w=800&q=80',
  },
};
